title: National Council on Disability
email: nsabula@ncd.gov
description: >- # this means to ignore newlines until "baseurl:"
  An independent federal agency committed to
  disability policy leadership since 1978
baseurl: ""
logo: true
# url: "https://ncd.gov" # the base hostname & protocol for your site, e.g. https://example.com.
  # Required to support the jekyll-sitemap plugin below.
  # Uncomment the url line when ready to push to production. If using different branches for multiple
  # custom domains, edit this url parameter in the relevant branch to match the relevant custom domain.

# Twitter handle. Only the handle, not the URL.
twitter: NCDgov

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  # agency: your-agency

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: About Our Council
    children:
      - name: Purpose and Vision
        url: /vision/
      - name: Members and Leadership
        url: /members-and-leadership/
      - name: Meetings & Events
        url: /meetings/
      - name: Committees and Communities
        url: /committees-communities/
  - name: Policies, Publishing & Resources
    children:
      - name: Reports
        url: /reports/
      - name: Correspondence
        url: /correspondences/
      - name: Resources
        url: /resources/
      - name: FAQ
        url: /resources/faq/
  - name: Accountability
    children:
      - name: Accountability
        url: /accountability/
      - name: Vulnerability Disclosure Policy
        url: /accountability/vulnerability-disclosure-policy/
      - name: Buy American Act Reports
        url: /accountability/buy-american-act-reports/
      - name: Government Performance and Results Act Reports
        url: /accountability/government-performance-and-results-act-reports/
      - name: Congressional Budget Justification Reports
        url: /accountability/congressional-budget-justification-reports/
      - name: Financial Audit Reports
        url: /accountability/financial-audit-reports/
      - name: NCD Strategic Plan
        url: /accountability/ncd-strategic-plan/
      - name: NCD Annual Employee Survey
        url: /accountability/ncd-annual-employee-survey/
      - name: NCD Bylaws
        url: /accountability/ncd-bylaws/
      - name: No Fear Act
        url: /accountability/no-fear-act/
      - name: Office of Special Counsel
        url: https://osc.gov/
  - name: News
    url: /newsroom/


secondary_navigation:
  - name: Contact US
    url: "contact"
  - name: Accountability
    url: "Accountability"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # You should not change this.
  endpoint: https://search.usa.gov

  # replace this with your search.gov account
  affiliate: federalist-uswds-example

  # replace with your access key
  access_key: xX1gtb2RcnLbIYkHAcB6IaTRr4ZfN-p16ofcyUebeko=

  # this renders the results within the page instead of sending to user to search.gov
  inline: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  pages:
    output: true
    permalink: /:path/
  accountability:
    output: true
    permalink: /accountability/:name/
  committees-communities:
    output: true
    permalink: /committee-community/:name/
  correspondence:
    output: true
    permalink: /correspondence/:name/
  members-and-leadership:
    output: true
    permalink: /members-and-leadership/:name/
  meetings:
    output: true
    permalink: /meeting/:name/
  policy-areas:
    output: false
    permalink: /policy-areas/:name/
  publications:
    output: true
    permalink: /publications/:path/
  resources:
    output: true
    permalink: /resources/:path/
  reports:
    output: true
    permalink: /report/:name/

permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap # See additional instructions for url parameter above.
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 5
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock

assets:
  sources:
    - _assets/uploads
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist
